### ISSUE TITLE
Clean up project - unnecessary file? 

### ISSUE THREAD

**Issue by munje** [bvantagelimited/mobile-sdk-showcase-apps#2]
Do we need this file:
https://github.com/bvantagelimited/mobile-sdk-showcase-apps/blob/master/package.json

and if we need it, why we have this hardcoded:
"react-native-ipification-library": "/Users/nguyenhuutinh/IPProjects/reactnative/IPification-React-Native-Plugin/NativeIPificationLibrary/"

it has a reference to your file system: 'nguyenhuutinh' ...

**Comment by nguyenhuutinh** [comment]
ok. I have removed it
