### ISSUE TITLE
Client secret in code

### ISSUE THREAD

**Issue by munje** [bvantagelimited/mobile-sdk-showcase-apps#3]
Check those files:
1. https://github.com/bvantagelimited/mobile-sdk-showcase-apps/blob/89ddafa40c423f1b1284801364ca42ff9ed0c0bf/ipification-sdk-xamarin-csharp/DemoApplication/DemoApplication/login/LoginPage2.xaml.cs

  { "client_secret" , "d6d710ee-68db-4913-934e-b02330523549" },

2. https://github.com/bvantagelimited/mobile-sdk-showcase-apps/blob/da2c4258151aece13a6ac4194f797ac1e5a49ba2/ipification-sdk-react-native-js/App.js

  'client_secret': 'd6d710ee-68db-4913-934e-b02330523549',

**Comment by nguyenhuutinh** [comment]
updated
