### ISSUE TITLE
Documentation on react-native usage?

### ISSUE THREAD

**Issue by miki995** [bvantagelimited/mobile-sdk-showcase-apps#5]

**Comment by munje** [comment]
hi @miki995 ,
we have the docs for the ReactNative but we haven't got a time yet to migrate it to the our developer portal like we have for Androifd and iOS .. 
https://developer.ipification.com/#/android/latest/
https://developer.ipification.com/#/ios/latest/

Until we migrate it you can take a look into doc version: https://docs.google.com/document/d/1UlIYjE9Av2D8OqXRPzI-FhGqzIOFmjHKq-AYP4QX1sg/

**Comment by miki995** [comment]
Thank you very much!
